/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_utils_NativeImageUtils */

#ifndef _Included_com_example_utils_NativeImageUtils
#define _Included_com_example_utils_NativeImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_utils_NativeImageUtils
 * Method:    getImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_utils_NativeImageUtils_getImage
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
